# Generated by Django 5.2.6 on 2025-09-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_numeric_id', models.BigIntegerField(unique=True)),
                ('id_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_treino_criado', models.BigIntegerField(blank=True, null=True)),
                ('letra_treino', models.CharField(max_length=5)),
                ('id_exercicio', models.IntegerField()),
                ('nome_exercicio', models.CharField(max_length=100)),
                ('series', models.IntegerField()),
                ('repeticoes', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='api.userid')),
            ],
        ),
    ]
